import React from 'react';
import './about-text.css';

export const AboutText = () => (
  <div className='about-text-container'>
    <p>I'm a <strong>full-stack + mobile developer</strong> from <strong>Germany</strong> that loves to <strong>build</strong> products <strong>fast</strong> and <strong>design</strong> features with the <strong>80:20</strong> rule.</p><p>I have delivered a cross-platform <strong>app</strong> using <strong>React Native</strong>, developed <strong>frontend</strong> applications with <strong>React</strong> and Angular and can build <strong>backend</strong> services in <strong>Node</strong>, C#, Java and Python.</p><p><strong>Clojure</strong> and <strong>ClojureScript</strong> are my favorite languages. I'm also interested in <strong>F#</strong>, Kotlin and Elm. Most of my time is spent writing <strong>TypeScript</strong> and <strong>JavaScript</strong>, but I also had exposure to (excluding prev. mentioned) <strong>SQL</strong>, Haskell, PHP, C++, C, ASM.</p><p><strong>Modern tools</strong> and <strong>processes</strong> are <strong>important</strong> to me. I develop in an <strong>agile</strong> way, using <strong>CI/CD</strong> platforms, <strong>collaborative</strong> design tools and a <strong>digital-first</strong> approach.</p><p>I love <strong>working</strong> in a <strong>team</strong>, but I am also <strong>comfortable</strong> handling the entire feature <strong>planning</strong> and <strong>delivery</strong> process <strong>on my own</strong>. I have multiple years of experience using design tools like <strong>Figma</strong> and the <strong>Adobe</strong> Suite, have worked <strong>independently</strong> on an <strong>app</strong> for a small startup and have acted as a <strong>project-manager</strong> for multiple successful projects during my <strong>bachelor</strong> in applied <strong>computer science</strong>.</p>
    <p>The <strong>source code</strong> for my website can be found on my <a href="https://github.com/marlonschlosshauer/marlonschlosshauer.de">github</a> profile. The <strong>Figma file</strong> is available <a href="https://www.figma.com/file/erIcWhDdlNrVPMFnKPMk6X/marlonschlosshauer.de?node-id=103%3A16117">here</a>.</p>
  </div>
)

export default AboutText;
